#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Microsoft Windows 11" {
                insmod part_gpt
                insmod fat
                insmod chain
                search --no-floppy --fs-uuid --set=root E201-EEE3 --hint-efi=hd0,gpt1
                chainloader /EFI/Microsoft/Boot/bootmgfw.efi
        }



menuentry "Ubuntu 22" {
        search --no-floppy --set=root --fs-uuid 5772721d-ed47-484f-9bef-8f20f1e0bc61
        linux /boot/vmlinuz root=UUID=5772721d-ed47-484f-9bef-8f20f1e0bc61
        initrd /boot/initrd.img
}
